services:

  cassandra:

    image: cassandra:5.0

    container_name: cassandra

    hostname: cassandra

    ports:
      - "9042:9042"

    environment:
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 128M

    volumes:
      - ./docker/cassandra:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 20s
      timeout: 10s
      retries: 20

  cassandra-init:

    image: cassandra:5.0

    depends_on:
      cassandra:
        condition: service_healthy

    volumes:
      - ./docker/cassandra:/scripts

    entrypoint: ["/bin/bash","/scripts/init.sh"]