spring.application.name=insights-api-service

# -------------------------
# Cassandra
# -------------------------
spring.cassandra.contact-points=localhost
spring.cassandra.port=9042
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.keyspace-name=ad_insights
spring.cassandra.schema-action=NONE

# -------------------------
# Server
# -------------------------
server.port=8080

# -------------------------
# Actuator
# -------------------------
management.endpoints.web.exposure.include=health,info

# -------------------------
# Swagger
# -------------------------
springdoc.swagger-ui.path=/swagger-ui.html

# -------------------------
# Logging
# -------------------------
logging.level.root=INFO
logging.level.org.springframework.data.cassandra=INFO

# -------------------------
# Resilience4j (to be used later)
# -------------------------
resilience4j.retry.instances.cassandraRetry.max-attempts=3
resilience4j.retry.instances.cassandraRetry.wait-duration=2s